sudo: required
language: bash
services:
- docker
stages:
- build
before_script:
- docker login -u "${DH_USERNAME}" -p "${DH_PASSWORD}";
after_script:
- docker logout
jobs:
  include:
  - stage: build
    if: branch = master
    env:
    - IMAGE_NAME: node6
    - NODE_MAJOR_VERSION: 6
    script:
    - ENVIRONMENT=development ./build.sh "${DH_REPO}" "${IMAGE_NAME}" "NODE_CODE=v${NODE_MAJOR_VERSION}.x";
    - ENVIRONMENT=production ./build.sh "${DH_REPO}" "${IMAGE_NAME}" "NODE_CODE=v${NODE_MAJOR_VERSION}.x";
    - ENVIRONMENT=development COMMIT_MESSAGE="${TRAVIS_COMMIT_MESSAGE}" ./publish.sh "${DH_REPO}" "${IMAGE_NAME}";
    - ENVIRONMENT=production COMMIT_MESSAGE="${TRAVIS_COMMIT_MESSAGE}" ./publish.sh "${DH_REPO}" "${IMAGE_NAME}";
  - stage: build
    if: branch = master
    env:
    - IMAGE_NAME: node8
    - NODE_MAJOR_VERSION: 8
    script:
    - ENVIRONMENT=development ./build.sh "${DH_REPO}" "${IMAGE_NAME}" "NODE_CODE=v${NODE_MAJOR_VERSION}.x";
    - ENVIRONMENT=production ./build.sh "${DH_REPO}" "${IMAGE_NAME}" "NODE_CODE=v${NODE_MAJOR_VERSION}.x";
    - ENVIRONMENT=development COMMIT_MESSAGE="${TRAVIS_COMMIT_MESSAGE}" ./publish.sh "${DH_REPO}" "${IMAGE_NAME}";
    - ENVIRONMENT=production COMMIT_MESSAGE="${TRAVIS_COMMIT_MESSAGE}" ./publish.sh "${DH_REPO}" "${IMAGE_NAME}";
